---
name: Main
on: [push, pull_request]

jobs:
  pre-commit:
    name: Run `pre-commit`
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-tags depName=python/cpython
      PYTHON_VERSION: 3.12.3
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  test:
    name: Test the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - id: test-override-no_pr
        name: test-override-no_pr
        uses: ./
        with:
          branch-name: test-no_pr-DONOTREMOVE
          override: true
      - run: |
          [[ ${{ steps.test-override-no_pr.outputs.should-run }} == "true" ]]
      - id: test-override-pr
        name: test-override-pr
        uses: ./
        with:
          branch-name: test-pr-DONOTREMOVE
          override: true
      - run: |
          [[ ${{ steps.test-override-pr.outputs.should-run }} == "true" ]]
      - id: test-no_pr
        name: test-no_pr
        uses: ./
        with:
          branch-name: test-no_pr-DONOTREMOVE
          override: false
      - run: |
          [[ ${{ steps.test-no_pr.outputs.should-run }} == "true" ]]
      - id: test-pr
        name: test-pr
        uses: ./
        with:
          branch-name: test-pr-DONOTREMOVE
          override: false
      - run: |
          [[ ${{ steps.test-pr.outputs.should-run }} == "false" ]]
  release:
    name: Release
    needs:
      - pre-commit
      - test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Run `semantic-release`
        uses: codfish/semantic-release-action@b0e57c976bf8f74b2454f59a30e4a1b5f11727b4 # v3.3.0
        id: sem-rel
        with:
          plugins: |
            [ "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update branch for major version
        if: steps.sem-rel.outputs.new-release-published == 'true'
        run: git push
             https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
             HEAD:refs/heads/v${{steps.sem-rel.outputs.release-major}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
